### ISSUE TITLE
too strict checking for revtex

### ISSUE THREAD

**Issue by TomVeeDee** [AASJournals/AASTeX60#113]
On line 280 of cls/aastex63.cls, there is a very strict check for the presence of package RevTex4-1. However, that has been superseded by RevTex4-2. The line should check for any RevTex package 4.1 _or above_ . 
It is not clear for me how to efficiently implement that. I have circumvented it for now by making a symlink to revtex4-2.cls with the name revtex4-1.cls.

**Comment by gregschwarz** [comment]
I did not know that there was a version 4-2! Thank you for letting us know about this so it can be addressed in the next version. We will have to make sure that there are no conflicts with 4-2 and the new features we have implemented in 6+.

**Comment by augustfly** [comment]
@gregschwarz did the revtex4.1 dependency make it into the forthcoming bug fix? Or did we delay it to a new version?

**Comment by gregschwarz** [comment]
We are punting that to the next non-bug release, v6.4.

**Comment by 2718d** [comment]
changing the requirement from revtex4-1 to revtex4-2 within aastex63 works, 
so [aastex631.cls](http://www.astro.gla.ac.uk/~eduard/aastex631.cls)  should be working fine with the latest revtex

**Comment by augustfly** [comment]
FYI: We are not able to test revtex4-2 comprehensively just yet, but I'm updating this thread to suggest that users can make a manual fix until we add it formally.  

FWIW TeXLive 2020 on macs contains both versions.  Clearly it is not true of MikeTeX and I'm not able to test TeXLive on linux. I don't know if this is an mac accident or not. The Mac TexLive 2020 distribution also includes totally deprecated packages like caption, which throw problems when users keep using them but try cross-compiling.

The temporary manual fix is (yes, I'm not fixing the strictness): 

https://github.com/AASJournals/AASTeX60/blob/3a75b1687c0219d0279ff9d9a41ad9b43fa2e7db/cls/aastex63.cls#L280-L286 


to 

```
 \IfFileExists{revtex4-2.cls}{
    \def\@revtex@cls{revtex4-2}
  }{
\typeout{^^J^^J Please update your system to include
revtex4-2.cls^^J^^J}\stop
  }
\def\@revtex@cls{revtex4-2}
```

**Comment by JerryBundler** [comment]
My problem was the following:
I would like to prepare a manuscript for ApJL using aastex63 with the latest miktex distribution on my local Windows machine. I got no pdf output and pdflatex told me "Please update your system to include revtex4-1.cls".

The temporary manual fix of augustfly solved my problem. (Now some warnings about stuck floats are still occurring but I can get along with that.)

Thank you, Gus and Greg!
